name: release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip" # caching pip dependencies

      - name: Set up build tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller

      - name: Compile single executable for Linux
        run: pyinstaller --onefile --noconfirm --clean --name=bitsrun src/bitsrun/cli.py

      - name: Package binaries
        run: |
          cd dist
          tar -czvf bitsrun.tar.gz bitsrun
          cd -

      - name: Upload binaries to GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/bitsrun.tar.gz
          asset_name: bitsrun.tar.gz
          tag: ${{ github.ref }}
